apiVersion: v1
kind: Secret
metadata:
    name: url-shortener-secret
    labels:
        app: mongo
data:
    REDIS_HOST: "{REDIS_HOST}"
    REDIS_PORT: "{REDIS_PORT}"
    REDIS_PASS: "{REDIS_PASS}"
    MONGODB_URI: "{MONGODB_URI}"
---

